trigger: none

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    op: test
  steps:
  - template: install-deps-linux.yml
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    op: test
  steps:
  - template: install-deps-macos.yml
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    op: test
  steps:
  - template: install-deps-windows.yml
  - template: install-ldc-windows.yml
  - template: dub-build-windows.yml
