jobs:
- job: 'Linux_x86'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    arch: x86
  steps:
  - template: pipeline-linux.yml
- job: 'Linux_x86_64'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    arch: x86_64
  steps:
  - template: pipeline-linux.yml
- job: 'macOS_x86'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    arch: x86
  steps:
  - template: pipeline-macos.yml
- job: 'macOS_x86_64'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    arch: x86_64
  steps:
  - template: pipeline-macos.yml
- job: 'Windows_x86'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    arch: x86
  steps:
  - template: pipeline-windows.yml
- job: 'Windows_x86_64'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    arch: x86_64
  steps:
  - template: pipeline-windows.yml
