jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    arch: x86_64
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install upx-ucl
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml
  - template: upx-compress.yml

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    arch: x86_64
  steps:
  - script: brew install upx
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml
  - template: upx-compress.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    arch: x86_mscoff
  steps:
  - template: install-ldc-windows.yml
  - template: dub-build-windows.yml
