trigger:
  branches:
    include:
    - refs/tags/*
    exclude:
    - master
    - release/*

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    os_name: linux
  strategy:
    matrix:
      x86:
        build: release
        arch: x86
      x86_64:
        build: release
        arch: x86_64
  steps:
  - template: install-deps-linux.yml
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml
  - template: upload-archive-posix.yml

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    os_name: osx
  strategy:
    matrix:
      x86:
        build: release
        arch: x86
      x86_64:
        build: release
        arch: x86_64
  steps:
  - template: install-deps-macos.yml
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml
  - template: upload-archive-posix.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    os_name: windows
  strategy:
    matrix:
      x86:
        build: release
        arch: x86
      x86_64:
        build: release
        arch: x86_64
  steps:
  - template: install-deps-windows.yml
  - template: install-ldc-windows.yml
  - template: dub-build-windows.yml
  - template: upload-archive-windows.yml
