jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      x86:
        arch: x86
      x86_64:
        arch: x86_64
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install upx-ucl gcc-multilib
    displayName: 'APT packages installation'
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml
  - template: upx-compress.yml

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      x86:
        arch: x86
      x86_64:
        arch: x86_64
  steps:
  - script: brew install upx
    displayName: 'Homebrew packages installation'
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml
  - template: upx-compress.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      x86:
        arch: x86
      x86_64:
        arch: x86_64
  steps:
  - script: choco install 7zip
    displayName: 'Chocolatey packages installation'
  - template: install-ldc-windows.yml
  - template: dub-build-windows.yml
