jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    os_name: linux
  strategy:
    matrix:
      x86:
        build: release
        arch: x86
      x86_64:
        build: release
        arch: x86_64
      test:
        op: test
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install upx-ucl gcc-multilib
    displayName: 'APT packages installation'
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    os_name: osx
  strategy:
    matrix:
      x86:
        build: release
        arch: x86
      x86_64:
        build: release
        arch: x86_64
      test:
        op: test
  steps:
  - script: brew install upx
    displayName: 'Homebrew packages installation'
  - template: install-ldc-posix.yml
  - template: dub-build-posix.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    os_name: windows
  strategy:
    matrix:
      x86:
        build: release
        arch: x86
      x86_64:
        build: release
        arch: x86_64
      test:
        op: test
  steps:
  - script: choco install 7zip
    displayName: 'Chocolatey packages installation'
  - template: install-ldc-windows.yml
  - template: dub-build-windows.yml
